version: '3.8'

services:
  taskmaster:
    build: .
    container_name: taskmaster-daemon
    restart: unless-stopped
    
    # Network configuration
    ports:
      - "8080:8080"
    
    # Volume mounts for persistence
    volumes:
      - taskmaster-logs:/var/log/taskmaster
      - taskmaster-tmp:/tmp/taskmaster
      - ./presentation.config.json:/app/task.config.json:ro
    
    # Environment variables
    environment:
      - DOTNET_ENVIRONMENT=Production
      - TASKMASTER_CONFIG_PATH=/app/task.config.json
      - TASKMASTER_LOG_PATH=/var/log/taskmaster/taskmaster.log
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "pgrep", "-f", "Taskmaster"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Signal handling
    init: true
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Monitoring service
  taskmaster-monitor:
    image: alpine:latest
    container_name: taskmaster-monitor
    depends_on:
      - taskmaster
    volumes:
      - taskmaster-logs:/logs:ro
    command: >
      sh -c "
        while true; do
          echo '=== Taskmaster Logs ===' &&
          tail -f /logs/taskmaster.log 2>/dev/null || echo 'Log file not found yet...' &&
          sleep 30
        done
      "
    restart: unless-stopped

volumes:
  taskmaster-logs:
    driver: local
  taskmaster-tmp:
    driver: local